name: analytics
version: "1.0.0"
dbt-cloud:
  project-id: 390588
profile: analytics
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  analytics:
    cleanse_data:  # Subdirectory containing your `opportunities.sql` model
      +enabled: true  # Ensure models in this directory are enabled


